### PR TITLE
Use random token authentication

### PR DESCRIPTION
**Pull request by asiripanich**
@shankari hopefully this works. :)

### CODE REVIEW

**Comment by asiripanich** [comment]
cc @atton16

**Comment by asiripanich** [comment]
@shankari can we get your comment on this PR please.. :)

**Comment by asiripanich** [comment]
A video from running this in the devapp.
https://user-images.githubusercontent.com/17020181/118386780-36a61580-b65d-11eb-95c0-9bf247c3ba19.mp4

**Comment by shankari** [comment]
I am not sure you need the `SecretCheck` code, but it doesn't hurt. It effectively functions as a hardcoded API key. 
As you can see from https://github.com/e-mission/e-mission-docs/issues/628

If you set the auth method on the server (https://github.com/e-mission/e-mission-docs/issues/628) to `secret`, only tokens prefixed by the secret will be accepted by the server. In that case, you probably don't want to check in the secret, but instead, email it to me separately so I can configure it.

Alternatively, if you just want a random token, you can remove this like

```
    const comboToken = SecretCheck.SECRET + token;
```

and just log in with the autogenerated token and the `skip` auth on the server.

I am merging this anyway for now, so @asiripanich can test it out, but if you do want the `SecretCheck` functionality, I would strongly suggest reconfiguring the server, and sending me the secret privately.

**Comment by shankari** [comment]
@atton16 @asiripanich I have now deployed this, but you haven't merged from master.  There are a ton of conflicts while pulling the change. I ended up pulling to an older branch, but without the most recent updates to master, you might run into problems with running on recent emTripLog.

```
kshankar-35069s:e-mission-phone-deploy kshankar$ git checkout master
www/css/main.diary.css: needs merge
www/i18n/en.json: needs merge
www/index.html: needs merge
www/js/app.js: needs merge
www/js/control/general-settings.js: needs merge
www/js/diary/list.js: needs merge
www/js/diary/services.js: needs merge
www/js/intro.js: needs merge
www/js/tripconfirm/post-trip-prompt.js: needs merge
www/templates/diary/list.html: needs merge
www/templates/intro/consent.html: needs merge
www/templates/intro/intro.html: needs merge
www/templates/intro/sensor_explanation.html: needs merge
www/templates/main.html: needs merge
```

**Comment by asiripanich** [comment]
Hi Shankari

Any breaking changes since we last update?

**Comment by shankari** [comment]
I don't remember when you last updated. You should be able to look at the diffs between your branch and master to see what the changes are. All the changes should be related to an issue which outlines what the problem is. I moved to the most recent version of a bunch of plugins in Fall 2020, and that required some breaking changes to the UI-only update code.

**Comment by asiripanich** [comment]
Something went wrong.

186634604_237644941457954_7223506351420946163_n

**Comment by shankari** [comment]
Ah, I need to change the checked in connnection config to prompted auth.

**Comment by asiripanich** [comment]
I'm pulling updates from master to this branch right now. Will send in a new PR soon.

**Comment by shankari** [comment]
So we had the branch configured with google auth since that is what you used for the last study.
But now we want to use the random token.
But we can't use the random token with google auth in the `www/json/connectionConfig.json`
https://github.com/e-mission/cordova-jwt-auth/blob/732900be4dcdc6ff477ff4419ab580f9acb4bdf9/src/ios/BEMJWTAuth.m#L113

I changed and pushed `www/json/connectionConfig.json`
LMK if that fixes it. This is not related to the pull from master.

**Comment by asiripanich** [comment]
It works! Thank you so much Shankari

**Comment by shankari** [comment]
@asiripanich 
- You should still pull from master when you have a chance. Note that this will involve server upgrades as well.
- You should also decide if you need the `SecretCheck` functionality, and if so, ensure that the secret is not checked in to Github.

**Comment by asiripanich** [comment]
Sure we will do that. @atton16 rushed and accidentally checked that in. But we will fix them. :) Thanks Shankari.

**Pull request merged**
