### PR TITLE
Switched to Google Auth

### PR DESCRIPTION
**Pull request by hmharvey**

### CODE REVIEW

**Comment by hmharvey** [comment]
@shankari can we merge this branch?

**Comment by shankari** [comment]
Have you changed the server settings? Should I flip the client `connectionConfig.json` as well?

**Comment by hmharvey** [comment]
Yes please!

**Comment by shankari** [comment]
done. should be live in ~ 10 mins

**Comment by hmharvey** [comment]
Awesome, thank you!

**Pull request merged**
