### PR TITLE
Update the phone README

### PR DESCRIPTION
**Pull request by shankari**
To indicate:

1. How to embed cordova webviews
1. How development is much easier now

### CODE REVIEW

**Comment by shankari** [comment]
@sfwatergit, @joshzarrabi, I added instructions on integrating cordova webviews into the hybrid phone app. Hopefully this is more clear now. LMK if something is still unclear, and I'll fix it pretty quickly. I need to get this in place before Jilliana starts anyway.

This will be checked in at the same time as:
https://github.com/e-mission/e-mission-phone-cordova-plugins/pull/11/files

**Comment by shankari** [comment]
If you want to see the READMEs in a more readable way, you can see the versions on my forks:

https://github.com/shankari/e-mission-phone
https://github.com/shankari/e-mission-phone-cordova-plugins

**Comment by joshzarrabi** [comment]
I found it very clear and helpful.

**Comment by sfwatergit** [comment]
:+1:

**Pull request merged**
