### PR TITLE
Switched to google auth (copied from connectionConfig.googleauth.json…

### PR DESCRIPTION
**Pull request by trevor-wu**
….sample, updated login screen and consent form

Updated and formatted consent form to match most recent IRB revision.

### CODE REVIEW

**Comment by shankari** [comment]
Please indicate testing done. Code review is not a substitute for testing, and I will not review code that does not indicate how it has been tested.

Having said that, I will give you $10 tomorrow if this commit (https://github.com/e-mission/e-mission-phone/pull/555/commits/afe001f60532e6dbc6d6eff6c450ee01ee34e3e3) works.

**Comment by shankari** [comment]
I will say, however, that I am impressed with the cleanliness of this PR. One commit and a nice description of what you did to generate it. Now you just need to get it to actually work...

**Comment by trevor-wu** [comment]
I took out the connectionConfig file to not reveal any keys, this pr is just the updated consent form on the phone.

**Comment by shankari** [comment]
@trevor-wu the consent form is not the most recent one.

**Comment by shankari** [comment]
obsoleted by #560

**Pull request closed without merging**
