### PR TITLE
changes and fixes to review system

### PR DESCRIPTION
**Pull request by trevor-wu**
- Cleaned up log and commits
- Yelpfusion.json.sample no longer shows up as new file

### CODE REVIEW

**Comment by shankari** [comment]
@trevor-wu can you please indicate the testing done?

**Comment by shankari** [comment]
Please do so by tonight, I would like to merge this change today since we have already postponed this for 2 weeks

**Comment by trevor-wu** [comment]
The api call was tested on the simulator and it does connect to Yelp using the API key I generated.

**Comment by shankari** [comment]
`yelpfusion.json` customized, and deployed.
Should be live in ~ 10 mins

**Pull request merged**
