### PR TITLE
Descriptive error 403 messages

### PR DESCRIPTION
**Pull request by sebastianbarry**
services.js
- Added processErrorMessages function which only checks for error 403 at the moment
- Added catch blocks for most of the functions that perform server calls

### CODE REVIEW

**Comment by sebastianbarry** [comment]
This is the updated PR to https://github.com/e-mission/e-mission-phone/pull/914

**Comment by sebastianbarry** [comment]
These are the only error messages I was able to replicate with the `error 403: Token not found on the server` error:

| While updating user, | While getting pipeline range timestamps, | While updating user, (separate location) |
:---:|:---:|:---:
| Simulator Screen Shot - iPhone 11 - 2023-04-28 at 10 07 15 | Simulator Screen Shot - iPhone 11 - 2023-04-28 at 10 07 35 | Simulator Screen Shot - iPhone 11 - 2023-04-28 at 10 08 03 |

**Comment by shankari** [comment]
@sebastianbarry are you planning to finish this PR before you stop working for NREL?

**Comment by sebastianbarry** [comment]
Here are the changes for the title of the error message to display `"Invalid OPcode: [original error title]"`

| | | |
:---:|:---:|:---:
| Simulator Screen Shot - iPhone 11 - 2023-04-28 at 15 43 23 | Simulator Screen Shot - iPhone 11 - 2023-04-28 at 15 43 25 | Simulator Screen Shot - iPhone 11 - 2023-04-28 at 15 43 34 |

@shankari  what do you think of this change?

**Comment by shankari** [comment]
@sebastianbarry LGTM! go ahead and push those changes. I think that's it for this PR

**Comment by sebastianbarry** [comment]
Now the code is much cleaner while being modular and displaying the same result and functionality

**Comment by shankari** [comment]
@sebastianbarry this doesn't affect you any more, but FYI, I am squash-merging this, so you won't be able to use this branch any more. Hopefully, by the time you are back, the phone codebase will be completely different.

**Comment by shankari** [comment]
For the record, since we have made the change in `displayError`, I don't think we need all the catch blocks in `service.js`.
but it doesn't hurt anything, and we will be changing this anyway as part of the rewrite.
Maybe I will try to remove them in a future commit.

**Review by shankari — APPROVED** [review]

**Pull request merged**
