### PR TITLE
Update Consent Form and Login Page

### PR DESCRIPTION
**Pull request by trevor-wu**
-Login page now says login with google instead of login via token list
-Consent form updated to latest language in approved IRB proposal
-Tested on IOS simulator

### CODE REVIEW

**Comment by shankari** [comment]
Please update with testing done.

**Comment by trevor-wu** [comment]
Login Screen Change: Screen Shot 2019-04-17 at 9 56 00 PM
Consent Form Change: 
Screen Shot 2019-04-17 at 9 55 40 PM
Screen Shot 2019-04-17 at 9 55 50 PM

**Comment by shankari** [comment]
LGTM! Good job on the clean PR!

**Comment by shankari** [comment]
deployed, should be live in ~ 10 mins

**Pull request merged**
