### PR TITLE
Upgrade the phone repo to api version 22 and cordova 5.0.0

### PR DESCRIPTION
**Pull request by shankari**
This is a pretty straightforward change in which I basically:
 - copied over the new cordova libs
 - copied over the new plugins
 - copied over the new javascript/html code
    
The main non-obvious changes were to:
 - write a script that updates the cordova libs
 - massage the application build.gradle to make it work

### CODE REVIEW

**Comment by shankari** [comment]
@joshzarrabi @sknapp, this is the change to move to api 22 for the main phone code, as opposed to the data collection library. I don't have a pull request builder (prb) set up for the data collection code, but I do for this, and as we can see, it failed.

I'll wait until you upgrade the servers and then merge...

**Comment by shaneknapp** [comment]
jenkins, test this please

**Comment by shaneknapp** [comment]
jenkins, test this please

**Comment by shaneknapp** [comment]
jenkins, test this please

**Pull request merged**
