### PR TITLE
Add codecov report on Github Action

### PR DESCRIPTION
**Pull request by jiji14**
#### Related Issue 
[Estimate code coverage](https://github.com/e-mission/e-mission-docs/issues/1023)

#### How to work 
When we submit Pull Request, `Codecov`report will be automatically generated.

### CODE REVIEW

**Comment by shankari** [comment]
@jiji14 alas,

https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.

We ran into this recently with @nataliejschulz; she can confirm.

Does codecov have a suggested workaround for open source projects, which will, of course, mostly follow the fork and pull request model?

**Comment by shankari** [comment]
Answering my own question, it looks like it does, in issue #29 of https://github.com/codecov/codecov-action

**Comment by jiji14** [comment]
@shankari 
We are almost there for code coverage, and I need you to do one more thing to add a coverage report in the comments.

<br />

Even though I connected the e-mission-phone project to Codecov, the reports didn't show up in the comments. I had a few guesses.

1. It might be because it was the first PR for Codecov. I mocked the situation with the test repository, but the report didn't show up even on the second PR.
2. It might be because I deleted the token in the workflow. I also added the token again and then checked, but it didn't work either.
3. There might be a setting for the comments. Upon checking the issue page on Codecov, I found a similar issue: [code cov comment is not added to the PR](https://github.com/codecov/codecov-action/issues/936).

<br />

**The problem was that I missed connecting with the [GitHub Apps - Codecov](https://github.com/apps/codecov).** After completing this step, I could see the report in the comments on my test repository.

Can you please follow these steps? 

1. Go to the [GitHub Apps - Codecov](https://github.com/apps/codecov) page.

<br />

2. Click on Configure.
Screenshot 2023-11-29 at 11 56 18 AM

<br />

3. Select repositories > e-mission-phone and click Save.
Screenshot 2023-11-29 at 11 57 35 AM

<br />

Thanks for being patient with me! 😃

**Comment by shankari** [comment]
@jiji14 I had already added it as a GitHub app
Screen Shot 2023-12-01 at 11 04 32 PM

and there was a message indicating that this will work once this PR is merged
https://github.com/e-mission/e-mission-phone/pull/1108#issuecomment-1830658923

Is that not good enough? I didn't merge because you didn't indicate that the changes were done...

**Comment by jiji14** [comment]
@shankari 
Screenshot 2023-12-01 at 8 09 10 PM

This is the codecov report I received from my personal project, so I expected to see the coverage result before merging it. Initially, I thought the app didn't connect with the e-mission-phone repository. As you commented, I now understand that we will receive the coverage report after merging it. Can you please merge this PR? Thank you :D

**Comment by shankari** [comment]
Fingers crossed!

**Pull request merged**
