### PR TITLE
Fixed button(s)

### PR DESCRIPTION
**Pull request by niccolopaganini**
- Wide buttons in the demographics page
- Issue for reference: [1015](https://github.com/e-mission/e-mission-docs/issues/1015)

### CODE REVIEW

**Comment by niccolopaganini** [comment]
Prettier failed, running through prettier...

**Comment by niccolopaganini** [comment]
Seems like all the tests are passing...

**Comment by shankari** [comment]
@niccolopaganini please indicate testing done before submitting for review.

**Comment by JGreenlee** [comment]
@niccolopaganini For a small UI bugfix like this, screenshots (like before vs. after) would be sufficient for demonstrating "testing done". We just need to see that it was fixed.

**Comment by niccolopaganini** [comment]
For the before refer [Issue 1015](https://github.com/e-mission/e-mission-docs/issues/1015)


### Here's the picture of the after:

**Review by JGreenlee — APPROVED** [review]

**Pull request merged**
