### PR TITLE
Fixed Confirm All

### PR DESCRIPTION
**Pull request by joshzarrabi**
We updated the code in ConfirmSectionListActivity.java to create a new page when confirm all was hit, and we cleaned up ConfirmmSectionActivity.java a tiny bit, no substantive changes there though.

As for testing, we needed a way to trick the server into sending my android phone a bunch of trips that were already classified, so we changed getUnclassifiedSections() in tripManager.py to stop filtering out results, and then connected the phone to the local database and uploaded the new data to the phone. After force syncing we were able to get many old trips to show up on the phone, and we were able to make sure our front end code worked.

### CODE REVIEW

**Comment by shankari** [comment]
Can you also update the testing done?

**Comment by shankari** [comment]
Ignore the comment by Jenkins - I'm trying to set up automated build and test for the projects.
The only thing that you need to do in order for me to pull this is to update the steps that you used for testing.

@joshzarrabi @lechiang

**Comment by shankari** [comment]
@joshzarrabi @lechiang, waiting for a description of the tests run before I can merge this change...

**Comment by joshzarrabi** [comment]
Okay, do you want us to upload the new code, or just describe what we did?

**Comment by shankari** [comment]
Is there new code (i.e. automated test case)? If so, it would be great to upload it.
If not, just describe what you did.

**Comment by joshzarrabi** [comment]
Okay, should i just email you the description or add it on the pull request?

Josh

**Comment by shankari** [comment]
Add it on the pull request - it is a much more permanent record...

**Comment by shankari** [comment]
ok to test

**Comment by shankari** [comment]
this is ok to test

**Pull request merged**
