### PR TITLE
Add explanations for relaxing background restrictions on samsung and …

### PR DESCRIPTION
**Pull request by shankari**
…huawei

@asiripanich I don't have a way to test this because I don't have either a Huawei or a Samsung.

The Huawei fix is documented here https://stackoverflow.com/questions/31638986/protected-apps-setting-on-huawei-phones-and-how-to-handle-it and was also reported by @PatGendre 
The Samsung fix was reported by you.

With these changes, we can cover the two worst offenders in https://dontkillmyapp.com/ but it is not a comprehensive list.

Thoughts?

### CODE REVIEW

**Comment by shankari** [comment]
Testing done: doesn't break anything. I am unable to test further right now since I don't have access to either Huawei or Samsung phones.

**Comment by asiripanich** [comment]
Looks good to me. Please merge. ;)

**Comment by PatGendre** [comment]
Hi FYI currently I don't have a Huawei phone anymore for testing. anyway your approach seems very sound.

**Comment by shankari** [comment]
@asiripanich Please report the results of field-testing this approach in your study. Was it confusing? Was it clear?

I can then cherry-pick this change (potentially with some modifications) into master.

**Comment by asiripanich** [comment]
I will need to ask the impacted user for feedback. 

By the way, are you sure that all samsung phones have the same battery management feature?

**Comment by shankari** [comment]
I don't. I don't have any samsung phones. We could change the text from "Your phone restricts app operation in the background." -> "Some Samsung phones restrict app operation in the background."

I would also check with the other samsung user to confirm that everything is actually working. Maybe it's not working and they are too busy to report it.

**Comment by PatGendre** [comment]
@shankari that's great that you could get the device manufacturer programmatically :-)   
For Huawei the text explanations is fine, AFAIK!   
I have no idea how many small phone vendors restrict background apps, though, but now we have a solid way of adding new ones to the list, thanks.

**Pull request merged**
