### PR TITLE
Fix 'today' in the datepicker

### PR DESCRIPTION
**Pull request by shankari**
This involved two fixes:
- recreating the config on resume so that the end date is reset (`list.js`), and
- setting "today" to the correct date when the datepicker is opened
    (`ionic-datepicker.bundle.min.js`)

I have also added build instructions to my fork of the ionic-datepicker repo,
but in case I delete the fork later, the instructions are:

Install node 10.19.0 ([gulp-sass will fail for more recent version of node](https://github.com/nodejs/node-gyp/issues/1763))

```
node -v
v10.19.0
```

Install and check gulp version

```
npm install
npm list | grep gulp
├─┬ gulp@3.9.0
```

Build

```
npx gulp build
```

Testing done:

Followed the steps in https://github.com/e-mission/e-mission-docs/issues/531#issuecomment-626220310
Both end date and today are updated correctly

### CODE REVIEW

**Comment by shankari** [comment]
@asiripanich can you please review this? I will then merge and deploy. Please test so that I can merge to master.

**Comment by asiripanich** [comment]
sure!

**Comment by shankari** [comment]
@asiripanich is that a review?

**Comment by asiripanich** [comment]
@shankari I dont have the dev environment setup on my machine and @atton16 is not reachable. 

I’m afraid this is going to take time if we have to wait for my review. Is it possible to merge and test instead?

**Comment by shankari** [comment]
by review, I mean look at the code. I already tested it (see the "testing done" in the commit)

**Comment by asiripanich** [comment]
Looks good to me.

**Comment by asiripanich** [comment]
Could you please rebase and merge this pr?

**Comment by shankari** [comment]
why do I need to rebase? It is already to rciti1...

**Comment by asiripanich** [comment]
Ahh sorry my bad..

**Comment by asiripanich** [comment]
Tried the testing steps on my device and can report that the issue no longer exists.

**Pull request merged**
