### PR TITLE
Implement initial integration with enketo-core with CSS and phonegap fixes

### PR DESCRIPTION
**Pull request by atton16**
- fix(enketo-survey): Fix broken UI due to css collision from `enketo-core` css
- fix: Fix phonegap autoreload

### CODE REVIEW

**Comment by shankari** [comment]
@atton16 as I said in https://github.com/e-mission/e-mission-phone/pull/563#issuecomment-489870471 your changes are to `formhub-print.css` which should only be used for `media=print`. Since this is a screen, I am not even sure that css file applies.
Can you also make similar changes for `formhub.css` and try it out? Or at least update the PR so that I can try it out?

**Comment by shankari** [comment]
@atton16 I take back https://github.com/e-mission/e-mission-phone/pull/569#issuecomment-492300773 I see that that you did include both - github had just hidden the changes to `formhub.css` because they were too large. Have you actually tested with this PR?

**Comment by atton16** [comment]
I have tested but as you mentioned that `formhub-print.css` should be use only for printing.

My index.html has this. (I think this is what you have originally, I didn't modified it)

```
<link href="manual_lib/enketo/css/formhub.css" media="all" rel="stylesheet">
<link href="manual_lib/enketo/css/formhub-print.css" media="print" rel="stylesheet">
```

**Comment by shankari** [comment]
> As you mentioned that formhub-print.css should be use only for printing, my index.html has this. (I think this is what you have originally, I didn't modified it)

That is what the enketo sample code has by default as well. The `print.css` should not affect anything since it should only be used when `media=print`

> I have tested and it is working perfectly.

So is the issue with screen displacement also fixed? Do you want me to just merge this?

**Comment by shankari** [comment]
@atton16 is this ready to merge, or do you want my help in testing further, specially wrt displacement of the trip UI?

**Comment by shankari** [comment]
@atton16 @asiripanich while waiting for you to respond, I went ahead and tested, reproduced and fixed the iOS offset issue. Feel free to pull it.

Note that I pulled master into `xlsform_survey_support` to resolve a merge conflict, so it now includes all the changes in #553 which touch the same files as your mode and purpose changes.
So you can either:
- cherry pick my last commit or pull from the branch and resolve the merge conflicts, or
- if you don't have substantial changes on your branch, maybe we can delete your branch and recreate from master.

Just let me know what you prefer.

**Comment by shankari** [comment]
According to me, next steps are:
- @asiripanich expressed interest in loading the survey from a server and not from the phone client, so that you don't have to send a PR every time you want to update the survey. I would suggest switching the `form_location` to one that is on some server. Maybe the e-mission server, but really, it could be on a gist or in github or anything.
- @asiripanich needs to design the real survey, potentially with `external` fields to customized based on user profile data.
- @atton16 needs to move the button to launch the survey to someplace more meaningful (unsure where that is), populate the survey based on the profile, parse and display the results, and store them back to the server. This may involve xml -> json conversion, but it looks like enketo includes one because it has the line

```
const parser = new DOMParser();
```

**Comment by shankari** [comment]
@atton16 
1. the complementary xform transformer looks cool! Can you add a README on how to use it?
1. I am going to merge this now, but did you also want to host the json files on a server somewhere so that you can update it without submitting a PR?

**Comment by shankari** [comment]
@atton16 were there any challenges in resolving merge conflicts?

**Comment by shankari** [comment]
deployed; should be live in ~ 10 mins

**Comment by asiripanich** [comment]
Hi Shankari, the recent update is causing the app to not work properly. The screen goes entirely blank.

**Comment by shankari** [comment]
It must be an issue with the merge. Master is fine, and I didn't have any merge conflicts when I deployed.

@atton16 did you test the changes before submitting the PR? I don't typically test the changes to branches other than master.

**Comment by atton16** [comment]
The functionality is still under development.

It is my mistake that I forgot I have filed a PR and keep pushing the code for the next version without knowing that the PR is still open.

It would be nice if you could revert the deployment.

**Comment by shankari** [comment]
@atton16 although I didn't test the change, I did review it, and it is essentially a pull from #563 + some forms. I don't see any additional changes to the javascript code.

We are pretty sure that #563 works because I have deployed it to the https://e-mission.eecs.berkeley.edu/#/client_setup?new_client=martanetworksp18&clear_usercache=true&clear_local_storage=true branch and it works.

```
$ git branch
...
  deploy-upload-interscity
* deploy-upload-marta-network-sp18

$ git pull https://github.com/shankari/e-mission-phone.git xlsform_survey_support
From https://github.com/shankari/e-mission-phone
 * branch            xlsform_survey_support -> FETCH_HEAD
Already up to date.
```

So I suspect that the WSOD is due to a merge conflict - the changes that I made to master to improve the list mode and purpose selection overlap significantly with the changes that you had made. That is why I asked about merge conflicts in the earlier comment (https://github.com/e-mission/e-mission-phone/pull/569#issuecomment-494061688)

I strongly suggest that you resolve merge conflicts before making more significant changes so that you start from a clean base.

**Comment by shankari** [comment]
@atton16 @asiripanich so the greentrip team (@sam11b) reported a similar issue. However, in their case, I knew that their merge worked because I did the merge and I tested after it.

So I connected a debugger, and it turned out that the change that enables the live reload breaks the deployment channel updates.

The errors in the debugger were

```
cordova.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
```

which then obviously led to 

```
jquery.min.js:2 jQuery.Deferred exception: Cannot read property 'log' of undefined TypeError: Cannot read property 'log' of undefined
    at Object.loggerJs.log (file:///data/user/0/edu.berkeley.eecs.embase/app_48b32ad6-3ac8-48ac-a7eb-1f1fe81fcd4a/js/plugin/logger.js:6:24)
    at file:///data/user/0/edu.berkeley.eecs.embase/app_48b32ad6-3ac8-48ac-a7eb-1f1fe81fcd4a/js/app.js:39:12
```

and so on.

the martanetworksp18 channel has the following line in `index.html`

```
    <script src="cordova.js"></script>
```

but the greentrip client has 

```
    <script type="text/javascript" src="cordova.js"></script>
```

Removing the `text/javascript` and re-deploying fixed it!

I will remove the `text/javascript` from the deployment channel *only* to keep live reload working on the dev branches.

**Comment by atton16** [comment]
> @atton16 @asiripanich so the greentrip team (@sam11b) reported a similar issue. However, in their case, I knew that their merge worked because I did the merge and I tested after it.
> 
> So I connected a debugger, and it turned out that the change that enables the live reload breaks the deployment channel updates.
> 
> The errors in the debugger were
> 
> ```
> cordova.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
> ```
> 
> which then obviously led to
> 
> ```
> jquery.min.js:2 jQuery.Deferred exception: Cannot read property 'log' of undefined TypeError: Cannot read property 'log' of undefined
>     at Object.loggerJs.log (file:///data/user/0/edu.berkeley.eecs.embase/app_48b32ad6-3ac8-48ac-a7eb-1f1fe81fcd4a/js/plugin/logger.js:6:24)
>     at file:///data/user/0/edu.berkeley.eecs.embase/app_48b32ad6-3ac8-48ac-a7eb-1f1fe81fcd4a/js/app.js:39:12
> ```
> 
> and so on.
> 
> the martanetworksp18 channel has the following line in `index.html`
> 
> ```
>     <script src="cordova.js"></script>
> ```
> 
> but the greentrip client has
> 
> ```
>     <script type="text/javascript" src="cordova.js"></script>
> ```
> 
> Removing the `text/javascript` and re-deploying fixed it!
> 
> I will remove the `text/javascript` from the deployment channels _only_ to keep live reload working on the dev branches.

That is odd but if it make the UI working again please do it. At least we can prove that this part is the cause.

**Comment by shankari** [comment]
Already did. Yesterday afternoon. I loaded your client in the emulator and it is not WSODing. What do you see on your phone?

**Pull request merged**
