### PR TITLE
💅 Label Screen cleanup & polishing 

### PR DESCRIPTION
**Pull request by JGreenlee**
After converting the Label Screen UI to React components with https://github.com/e-mission/e-mission-phone/pull/993, there are several items to address.

This PR will fix regressions, tidy, and continue to improve usability.

### CODE REVIEW

**Comment by JGreenlee** [comment]
The above commits are minor cleanups I already had, but didn't want to tack onto #993 while it was being reviewed

**Comment by shankari** [comment]
> The most notable thing is that I implemented caching for the address names we fetch from OSM. I've always found it annoying that they're retrieved again on every app load.

Note that we are also signing up for a paid subscription to geofabrik.de. Once that is done, we can fill in the addresses on the server. Regardless, we will still need direct client calls for draft trips, so this is a useful fix. Just might be less cool down the road.

**Comment by JGreenlee** [comment]
Sounds cool!

I think this was still largely worthwhile because now we have a lightweight storage method to use instead of `localstorage` (on a true native app, `localstorage` will not exist) and I have figured out a process for caching, which we could do for other network calls down the line

**Review by shankari — APPROVED** [review]
LGTM!

**Pull request merged**
