### PR TITLE
Implement more complex user input matching

### PR DESCRIPTION
**Pull request by shankari**
This fixes https://github.com/e-mission/e-mission-docs/issues/423
The new implementation works properly for trip end prompts and matches them
correctly to both processed and cleaned trips.

This is essentially a bunch of additional logging + the improved implementation
outlined in https://github.com/e-mission/e-mission-docs/issues/423

Since the implementation differs for processed v/s cleaned trips, the
`getUserInputForTrip` function now takes in the entire trip wrapper, not just
the properties. The changes to `list.js` are basically to pass in the right
kind of object.

### CODE REVIEW

**Comment by shankari** [comment]
@atton16 @deepalics0044 since you reported these issues, would you like to review this change? The related issue has more details and testing information

**Comment by shankari** [comment]
For the record, testing logs and screenshots are at https://github.com/e-mission/e-mission-docs/issues/423#issuecomment-507934919

**Comment by atton16** [comment]
If I wanted to tested on PR https://github.com/e-mission/e-mission-phone/pull/581. Do I need to wait for this branch to be merged and pull it to my branch...?

**Comment by shankari** [comment]
@atton16 can I get an approval now that you know that the change works?
@deepalics0044 you might also want to test this out and if it addresses your concerns, merge to your branch

**Comment by atton16** [comment]
Approved.

**Pull request merged**
