### PR TITLE
Changes made for CISTUP task

### PR DESCRIPTION
**Pull request by deepalics0044**
Changes mention by K. Shankari for Project Assistantship selection process.

### CODE REVIEW

**Comment by shankari** [comment]
As requested in the challenge, please upload or send the video of you
testing the change.

Shankari

**Comment by deepalics0044** [comment]
I sent you the e-mail. Please check out.

**Comment by shankari** [comment]
This is the same as #453 but to the correct branch. Unfortunately, it has a conflict that needs to be resolved. Normally, I would ask the pull request creator (@deepalics0044) to resolve the conflict first, but we've gone through multiple rounds of this, so I'm going to be generous and resolve the conflict myself.

**Comment by shankari** [comment]
@deepalics0044 deployed. Should be live in ~ 10 mins if you want to try re-installing...

**Pull request merged**
