### PR TITLE
Add a button that launches the access map in an iab window

### PR DESCRIPTION
**Pull request by shankari**
UW team can experiment with `"_blank"`, `"_system"`, `"_self"` etc to see which UI:
a) works
b) feels intuitive

### CODE REVIEW

**Comment by shankari** [comment]
Works on iOS
[in_app_browser.mov.gz](https://github.com/e-mission/e-mission-phone/files/1692389/in_app_browser.mov.gz)

**Comment by Andrew-Tan** [comment]
Thank you for your effort! Currently considering two mechanism:
1. Use in-app browser
2. Open external browser with the link

**Comment by shankari** [comment]
@Andrew-Tan LMK what works! FYI using `"_system"` with the iab is supposed to open the page in the system browser instead of in a webview, so it should be easy to test out all the options :)

**Comment by Andrew-Tan** [comment]
Great! Thanks, will try that out.

**Comment by shankari** [comment]
closing this since @Andrew-Tan is already testing it out separately.

**Pull request closed without merging**
