### PR TITLE
Rciti1: merge all updates from master

### PR DESCRIPTION
**Pull request by atton16**
Trying to merge all updates from master

### CODE REVIEW

**Comment by asiripanich** [comment]
@atton16 can you indicate what are the errors that you are seeing?

**Comment by shankari** [comment]
@atton16 any updates to this?

**Comment by asiripanich** [comment]
@WilliamChan4 will send in another PR using the merge strategy discussed over our meeting. @shankari You can close this PR. Thanks! :)

**Comment by shankari** [comment]
Closing this since it is being replaced by a piece-wise integration into master.

**Pull request closed without merging**
