### PR TITLE
Update metrics.js

### PR DESCRIPTION
**Pull request by PatGendre**
comment out weekday exclusion L1162

### CODE REVIEW

**Comment by shankari** [comment]
@PatGendre can you add a screenshot showing the field working? I've been asking everybody to indicate testing done to avoid having me test out all the changes. We need to have automated testing at some point...

**Comment by PatGendre** [comment]
@Shankari I have not forgotten but I have to wait for the app update, Yann could not work on it yesterday

**Comment by PatGendre** [comment]
sorry for the long delay... here is a screenshot with the saturdays selectable

Screenshot_2019-05-07-11-10-56

**Comment by shankari** [comment]
Reopening so that I can merge :)

**Pull request merged**
