### PR TITLE
Editable mode & purpose confirm

### PR DESCRIPTION
**Pull request by atton16**

### CODE REVIEW

**Comment by shankari** [comment]
> The reason that we did not use the command you gave me is that our programmer reported that the command not found so we will investigate into that matter after this.

https://github.com/e-mission/e-mission-phone/blob/master/www/js/services.js#L232

**Comment by shankari** [comment]
> We knows this limitation and we are working on it.

ok, I am merging this for now. @asiripanich, bewarned while testing...

**Comment by shankari** [comment]
@atton16 @asiripanich deployed, should be live in ~ 10-20 mins

**Comment by asiripanich** [comment]
@shankari  Thanks heaps!

**Pull request merged**
